function(bridge_options target)
  if(MSVC)
    if(BRIDGE_SANITIZER)
      message(FATAL_ERROR "These sanitizer presets require GCC/Clang. Native MSVC sanitizer validation is not yet configured.")
    endif()
    target_compile_options(${target} PRIVATE /W4 /permissive-)
    target_compile_options(${target} PRIVATE
      "$<$<CONFIG:Release>:/pathmap:${PROJECT_SOURCE_DIR}=.>"
      "$<$<CONFIG:Release>:/pathmap:${PROJECT_BINARY_DIR}=./build>")
    if(BRIDGE_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE /WX)
    endif()
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Wconversion -Wsign-conversion)
    target_compile_options(${target} PRIVATE
      "$<$<CONFIG:Release>:-ffile-prefix-map=${PROJECT_SOURCE_DIR}=.>"
      "$<$<CONFIG:Release>:-ffile-prefix-map=${PROJECT_BINARY_DIR}=./build>")
    if(BRIDGE_WARNINGS_AS_ERRORS)
      target_compile_options(${target} PRIVATE -Werror)
    endif()
    if(BRIDGE_SANITIZER)
      if(NOT BRIDGE_SANITIZER MATCHES "^(address|undefined|thread)$")
        message(FATAL_ERROR "Unsupported sanitizer")
      endif()
      target_compile_options(${target} PRIVATE -fsanitize=${BRIDGE_SANITIZER} -fno-omit-frame-pointer -fno-sanitize-recover=all)
      target_link_options(${target} PUBLIC -fsanitize=${BRIDGE_SANITIZER})
    endif()
  endif()
  if(BRIDGE_CLANG_TIDY)
    find_program(BRIDGE_TIDY NAMES clang-tidy-19 clang-tidy-20 clang-tidy REQUIRED)
    set_target_properties(${target} PROPERTIES CXX_CLANG_TIDY "${BRIDGE_TIDY};--warnings-as-errors=*")
  endif()
endfunction()
