# Default to shared Qt runtimes; an explicit target triplet remains authoritative.
if(CMAKE_TOOLCHAIN_FILE MATCHES "vcpkg.cmake$" AND NOT DEFINED VCPKG_TARGET_TRIPLET)
  if(DEFINED ENV{VCPKG_DEFAULT_TRIPLET} AND NOT "$ENV{VCPKG_DEFAULT_TRIPLET}" STREQUAL "")
    set(VCPKG_TARGET_TRIPLET "$ENV{VCPKG_DEFAULT_TRIPLET}" CACHE STRING "Native SDK triplet")
  else()
    cmake_host_system_information(RESULT bridge_host_cpu QUERY OS_PLATFORM)
    if(bridge_host_cpu MATCHES "^(aarch64|arm64|ARM64)$")
      set(bridge_host_arch arm64)
    elseif(bridge_host_cpu MATCHES "^(x86_64|AMD64|amd64)$")
      set(bridge_host_arch x64)
    else()
      message(FATAL_ERROR "Specify VCPKG_TARGET_TRIPLET for this host architecture")
    endif()
    if(CMAKE_HOST_WIN32)
      set(bridge_host_os windows)
    elseif(CMAKE_HOST_APPLE)
      set(bridge_host_os osx-dynamic)
    elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
      set(bridge_host_os linux-dynamic)
    else()
      message(FATAL_ERROR "Specify a tested native VCPKG_TARGET_TRIPLET for this host")
    endif()
    set(VCPKG_TARGET_TRIPLET "${bridge_host_arch}-${bridge_host_os}" CACHE STRING "Native shared SDK triplet")
  endif()
endif()
